version: '3'
services:
    web:
        image: sarahat/detapp:1.0
        ports:
            - 8000:8000
        working_dir: /var/www/detapp
        command: php artisan serve --host=0.0.0.0 --port=8000
        depends_on:
            - mysqldb

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:4.7
        ports:
            - 8001:8000
        depends_on:
            - mysqldb
        environment:
            PMA_HOST: mysqldb

    mysqldb:
        image: mysql:5.7
        restart: on-failure
        environment:
            MYSQL_DATABASE: sandwich_os
            MYSQL_ROOT_PASSWORD: 123456
